### ISSUE TITLE
Emigration to VLIZ supported database

### ISSUE THREAD

**Issue by PieterjanVerhelst** [inbo/fish-tracking#50]
We are currently uploading the detection files from the folder '2015 and later' to the database. Files that will be uploaded from '2015 and later' will be put in the new folder 'Uploaded', which you can find in the folder 'Raw'.
Just to inform everyone ;-).

**Comment by damianooldoni** [comment]
@PieterjanVerhelst: can we close this issue?

**Comment by PieterjanVerhelst** [comment]
Yes
