### ISSUE TITLE
Loops in calculating receiver distances

### ISSUE THREAD

**Issue by PieterjanVerhelst** [inbo/fish-tracking#52]
Automatically calculating receiver distances in longitudinal networks works excellent. A new challenge is calculating distances when loops are present, due to parallel canals. For example, fish migrating through the Albert Canal have different options to get into the Schelde in Antwerpen:
1) migration along the Albert canal - calculating the distances works with the current script (prepare_dataset.R)
2) moving into parallel canals (the 'Kempische kanalen'), resulting in different possible distances to move from station A to B (see figure below; note that the 2 loops are connected to eachother at the cross section).
How could this be implemented in the script?
![ak_network_loops](https://cloud.githubusercontent.com/assets/10052950/22733220/3b5fd05e-edf1-11e6-9528-08c957d546cc.png)

**Comment by damianooldoni** [comment]
I close this issue as it is further discussed in a very similar way in #68.
