### ISSUE TITLE
Can we make this repo public?

### ISSUE THREAD

**Issue by damianooldoni** [inbo/fish-tracking#74]
@PieterjanVerhelst and I would like to move the code to calculate receiver distances following the shortest **aquatic** path to [actel](https://github.com/hugomflavio/actel/) package. Of course the author cannot see our code as this repo is private. There are many other ways to collaborate with him and show him the code we developed in this repo (e.g. export relevant code in a gist), but the question is: are there still reasons to maintain this repo private? At our side, there aren't.

**Comment by peterdesmet** [comment]
Done, can you update the README?

**Comment by PieterjanVerhelst** [comment]
Done ✔️
